### ISSUE TITLE
Best way to check tshark compatibility

### ISSUE THREAD

**Issue by techge** [vs-uulm/nemesys#5]
How can I test that my tshark version is working correct? I am currently using tshark 2.6.20 and have some problem using nemesys_fms.py and do not know if this is a problem with my pcaps/code/whatever or if this might be a compatibility issue you are warning when starting the fms code...

**Comment by skleber** [comment]
That is a little bit tricky, since each dissector is written by other authors and tshark seems to allow a lot of freedom about how a dissector may format its JSON representation. Thus, a failure may be caused by a specific dissector behaviour that I did not observe in the past and thus did not consider when parsing the JSON. In this case, the tshark output is not interpreted correctly and is thus "incompatible" in a way. On the other hand, it may simply be the case that I did not observe a specific field in any of my test cases for a protocol and thus did not add the definition. In this case it is a simple matter of defining it in the respective nemere.validation.messageParser.ParsingConstants subclass. This also lacks proper documentation, but if you encounter any such situation, I would be happy to assist. In this case, please add some details, e. g., the exception you encounter.

**Comment by techge** [comment]
I see that is most unfortunate, but makes sense somehow. Thank you very much for your detailed explanation! I will see if there are tshark related pecularities that I find and are not yet handled and report/open PR accordingly if I can...
