### ISSUE TITLE
[question] MessageComparator, tshark and pcaps

### ISSUE THREAD

**Issue by techge** [vs-uulm/nemesys#8]
As I am experiencing troubles with undeterministic output while trying the format match score function, I am wondering what reasons led to the decision to let every message be parsed separately by tshark instead of feeding a whole pcap and parsing the json of the whole pcap? Would it be feasible to refactor the code to accept a complete pcap instead to avoid all of the tshark threading stuff? Or is there a big no-no I am not seeing here?

I would pretty much like to have the possibility to insert pcaps instead of working with the specimenloader as this might be more generalized for the many different approaches people are using anyway. What do you think?

**Comment by skleber** [comment]
Actually `nemere.validation.messageParser.ParsedMessage.parseMultiple` does hand over chunks of messages for parsing by tshark in a single "transaction" and does not perform one call per message. The main reasons for this solution are:
* Starting a separate tshark process per message produces HUGE overhead and is impractical from a performance point of view.
* Thus, keeping a tshark instance running in the background to hand over byte streams to it for parsing saves a lot of time.
* Keeping track of which input message matches to which JSON output fails sometimes for large traces, thus I use chunks of 1000 messages that are handed over to tshark at once and wait for their output to be completed each time.
* I also had problems with tshark seemingly behaving differently depending on the system load or other reasons I could not determine - especially when running with an attached debugger. I think this is caused by some timing issues in piping input data in or piping output back into python. I added loads of checks, waiting cycles, and failsaves, but could not completely sort out this problem.

That said, you are free to optimize the robustness of the parsing if you can. I would like to see your proposals for this.

---

As for the SpecimenLoader: There are several relations and dependencies that I would not keep when doing a large refactoring of the codebase. However, I am lacking the time to do this thoroughly. Any ideas are welcome.
In any case you need to load a PCAP into Python one way or the other. SpecimenLoader hides some of the complexities but basically does just that. Plus it keeps each message as raw byte string (that is needed as imput for tshark) and the application layer message with the encapsulation interpreted. This could be solved using another kind of message representation than netzob's which might be an option but a lot of work to change the implementation. Again: any contributions welcome.

**Comment by techge** [comment]
Again, thanks a lot for the detailed explanation and notes. This helps me to decide for fixes and if they are useful anyway. I will see if I can change or just add things to get it working in other/different ways. Thanks a lot!
